#!/bin/bash

# Redirect all output (including error messages) to the log file
exec &> >(tee /home/agent/littleredrooster.log)

# Retrieve the magnet link from the command-line argument
magnet_link="$1"

# Log the received magnet link
echo "Received magnet link:
$magnet_link
"

# Check instant availability
instant_response=$(curl -s -G --data-urlencode "magnets[]=$magnet_link" "https://api.alldebrid.com/v4/magnet/instant?agent=myAppName&apikey=YOUR_API_KEY" 2>&1)

# Log the full Alldebrid API response for the instant availability check
echo "Alldebrid API response for instant availability check:
$instant_response
"
# Extract the download id from the magnet upload
instant_bool=$(echo $instant_response | jq -r '.data.magnets[0].instant')


# Log the extracted download ID
echo "AllDebrid:
$instant_bool
"

# Check if the file is instantly available
if $(echo "$instant_response" | jq -r '.data.magnets[0].instant') = "true"; then


    # Use curl to upload the magnet link to Alldebrid via API v4
    upload_response=$(curl -s -X POST -F "magnets[]=$magnet_link" "https://api.alldebrid.com/v4/magnet/upload?agent=script_uploader&apikey=YOUR_API_KEY" 2>&1)

    # Log the full Alldebrid API response for the magnet link upload
    echo "Alldebrid API response for magnet link upload:
    $upload_response
    "

    # Extract the download ID from the magnet upload API response
    download_id=$(echo $upload_response | jq -r '.data.magnets[0].id')

    # Log the extracted download ID
    echo "Extracted ID:
    $download_id
    "

    # Use the download ID to fetch the file URL
    file_response=$(curl -s -G --data-urlencode "id=$download_id" "https://api.alldebrid.com/v4/magnet/status?agent=myAppName&apikey=YOUR_API_KEY" 2>&1)

    # Log the full Alldebrid API response for the file URL
    echo "Alldebrid API response for file URL:
    $file_response
    "

    # Extract the file URL from the file response
    file_url=$(echo "$file_response" | jq -r '.data.magnets.links | map(select(.files[].n | test("\\.(mp4|mkv|mov|avi)$"))) | .[0].link')

    # Log the extracted file URL
    echo "Extracted file URL:
    $file_url
    "

    # Use file URL to fetch streaming URL
    streaming_response=$(curl -G --data-urlencode "link=$file_url" "https://api.alldebrid.com/v4/link/unlock?agent=myAppName&apikey=YOUR_API_KEY" 2>&1)

    # Log the full Alldebrid API response for the file URL
    echo "AllDebrid API response for file URL:
    $streaming_response
    "

    # Extract the streaming url from the file url
    streaming_url=$(echo "$streaming_response" | grep -Pzo "(?s)\{.*" | jq -r '.data.link')

    # Log the extracter streaming URL
    echo "Extracted streaming URL:
    $streaming_url"


    # Get user input
    echo -e "





























'Hey, you. You're finally awake.
You were trying to cross the border, right?
Walked right into that Imperial ambush,
same as us, and that thief over there.'
"



echo -e "\e[31m░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░▄▀▀▄░░░░░░░░░░░░░
░░░░░░▄▀▒▒▒▒▀▄░░░░░░░░░░░
░░░░░░░▀▌▒▒▐▀░░░░░░░░░░░░
░▄███▀░◐░░░▌░░░░░░░░░░░░░░
░░░▐▀▌░░░░░▐░░░░░░░░░░▄▀▀▀▄▄
░░▐░░▐░░░░░▐░░░░░░░░░█░▄█▀
░░▐▄▄▌░░░░░▐▄▄░░░░░░█░░▄▄▀▀▀▀▄
░░░░░░▌░░░░▄▀▒▒▀▀▀▀▄▀░▄▀░▄▄▄▀▀
░░░░▐░░░░▐▒▒▒▒▒▒▒▒▀▀▄░░▀▄▄▄░▄
░░░░▐░░░░▐▄▒▒▒▒▒▒▒▒▒▒▀▄░▄▄▀▀
░░░░░▀▄░░░░▀▄▒▒▒▒▒▒▒▒▒▒▀▄
░░░░░░░▀▄▄░░░█▄▄▄▄▄▄▄▄▄▄▄▀▄
░░░░░░░░░░▀▀▄▄▄▄▄▄▄▄▀▀░
░░░░░░░░░░░░▌▌░▌▌░░░
░░░░░░░░░░▄▄▌▌▄▌▌
\e[0m"

echo -e "
    Welcome to the Little Red Rooster Booster!
    Would you like to b'gawk this jawn now?

    \033[1m\033[5m*peck*\033[0m (y/n) \033[1m\033[5m*peck*\033[0m
    "
    read user_response

    if [[ $user_response = "y" ]]; then
        # Stream the download link using mpv
        echo "


        All the pretty 'lil hens know my name!:

        $streaming_url"
        mpv -really-quiet "$streaming_url" 2>&1
        mpv_status=$?

        # Log the mpv streaming status
        echo "



        She layin' them eggs: $mpv_status"

    else

        echo "



        The guffin' was roster boosted" && sleep 3

    fi

else

    echo -e "

    \033[1m*buh'\033[0m\033[1m\033[3mGAAWWWWKKK*\033[0m
    \033[1m*buh'\033[0m\033[1m\033[3mGAAWWWWKKK*\033[0m
    \033[1m*buh'\033[0m\033[1m\033[3mGAAWWWWKKK*\033[0m
    \033[1m*buh'\033[0m\033[1m\033[3mGAAWWWWKKK*\033[0m
    \033[1m*buh'\033[0m\033[1m\033[3mGAAWWWWKKK*\033[0m
    \033[1m*buh'\033[0m\033[1m\033[3mGAAWWWWKKK*\033[0m
    \033[1m*buh'\033[0m\033[1m\033[3mGAAWWWWKKK*\033[0m
    \033[1m*buh'\033[0m\033[1m\033[3mGAAWWWWKKK*\033[0m
    \033[1m*buh'\033[0m\033[1m\033[3mGAAWWWWKKK*\033[0m

    \033[1m\033[5m*peck*\033[0m
           \033[1m\033[5m*peck*\033[0m
                               \033[1m\033[5m*peck*\033[0m
              \033[1m\033[5m*peck*\033[0m      \033[1m\033[5m*peck*\033[0m
\033[1m\033[5m*peck*\033[0m
               \033[1m\033[5m*peck*\033[0m
                                           \033[1m\033[5m*peck*\033[0m
                           \033[1m\033[5m*peck*\033[0m
                                                      \033[1m\033[5m*peck*\033[0m
                 \033[1m\033[5m*peck*\033[0m
     \033[1m\033[5m*peck*\033[0m
                                                  \033[1m\033[5m*peck*\033[0m
                 \033[1m\033[5m*peck*\033[0m


    Don't you EVER suggest this magnet link again you little pop-tart.
    Don't even think about it....
    I can't even \033[3mlook\033[0m at you...... \033[1m*BAWK*\033[0m" && sleep 10

fi
